create table if not exists users
(
    id    bigint generated by default as identity,
    name  varchar(255) not null,
    email varchar(255) not null,
    constraint pk_user primary key (id),
    constraint unique_email unique (email)
);

create table if not exists requests
(
    id           bigint generated by default as identity primary key,
    description  varchar(255) not null,
    requester_id bigint       not null,
    created      timestamp without time zone not null,
    foreign key (requester_id) references users (id) on delete cascade
);

create table if not exists items
(
    id           bigint generated by default as identity primary key,
    name         varchar(255) not null,
    description  varchar(255) not null,
    is_available boolean,
    owner_id     bigint       not null,
    request_id   bigint,
    foreign key (owner_id) references users (id) on delete cascade,
    foreign key (request_id) references requests (id) on delete cascade
);

create table if not exists bookings
(
    id         bigint generated by default as identity primary key,
    start_date timestamp without time zone not null,
    end_date   timestamp without time zone not null,
    item_id    bigint,
    booker_id  bigint,
    status     varchar(100)                not null,
    foreign key (booker_id) references users (id) on delete cascade,
    foreign key (item_id) references items (id) on delete cascade
);

create table if not exists comments
(
    id        bigint generated by default as identity primary key,
    text      varchar(255)                not null,
    item_id   bigint,
    author_id bigint,
    created   timestamp without time zone not null,
    foreign key (author_id) references users (id) on delete cascade,
    foreign key (item_id) references items (id) on delete cascade
)